# Generated by Django 2.2.7 on 2020-09-23 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200920_1851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.AlterField(
            model_name='userplaylist',
            name='song',
            field=models.ManyToManyField(related_name='playlist_songs', to='music.Song'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(null=True, upload_to='static/image/avatar/')),
                ('gender', models.CharField(choices=[('M', '남성'), ('F', '여성')], max_length=1, null=True)),
                ('age', models.CharField(choices=[('0', '10세 이하'), ('1', '10대'), ('2', '20대'), ('3', '30대'), ('4', '40대'), ('5', '50대 이상')], max_length=1, null=True)),
                ('is_signed_up', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
