# Generated by Django 2.2.7 on 2020-10-02 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201002_1546'),
        ('accounts', '0005_auto_20200925_1119'),
    ]

    operations = [
    ]
