# Generated by Django 2.2.7 on 2020-09-27 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='artist',
            name='debue',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='artist',
            name='member',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='artist',
            name='type',
            field=models.CharField(max_length=300),
        ),
    ]
