# Generated by Django 2.2.7 on 2020-09-30 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20200929_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='album',
            name='released_date',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='artist',
            name='debue',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='artist',
            name='member',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='artist',
            name='type',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=300, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='genre',
            name='num',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='song',
            name='released',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='song',
            name='type',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
