# Generated by Django 2.2.7 on 2020-09-30 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20200930_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='youtube_id',
            field=models.CharField(default='', max_length=300, null=True),
        ),
    ]
