# Generated by Django 2.2.7 on 2020-09-30 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_song_youtube_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='youtube_id',
            new_name='src',
        ),
    ]
